/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeRecoveryCodeRouteImport } from './routes/welcome.recovery-code'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRecoveryCodeRoute = WelcomeRecoveryCodeRouteImport.update({
  id: '/welcome/recovery-code',
  path: '/welcome/recovery-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/recover': typeof RecoverRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/welcome/recovery-code': typeof WelcomeRecoveryCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/recover': typeof RecoverRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/welcome/recovery-code': typeof WelcomeRecoveryCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/recover': typeof RecoverRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/welcome/recovery-code': typeof WelcomeRecoveryCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/recover'
    | '/signin'
    | '/signup'
    | '/welcome/recovery-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/recover'
    | '/signin'
    | '/signup'
    | '/welcome/recovery-code'
  id:
    | '__root__'
    | '/'
    | '/device'
    | '/recover'
    | '/signin'
    | '/signup'
    | '/welcome/recovery-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeviceRoute: typeof DeviceRoute
  RecoverRoute: typeof RecoverRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  WelcomeRecoveryCodeRoute: typeof WelcomeRecoveryCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/recovery-code': {
      id: '/welcome/recovery-code'
      path: '/welcome/recovery-code'
      fullPath: '/welcome/recovery-code'
      preLoaderRoute: typeof WelcomeRecoveryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeviceRoute: DeviceRoute,
  RecoverRoute: RecoverRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  WelcomeRecoveryCodeRoute: WelcomeRecoveryCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
