/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeRecoveryCodeRouteImport } from './routes/welcome.recovery-code'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as OauthCompleteRouteImport } from './routes/oauth.complete'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRecoveryCodeRoute = WelcomeRecoveryCodeRouteImport.update({
  id: '/welcome/recovery-code',
  path: '/welcome/recovery-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const OauthCompleteRoute = OauthCompleteRouteImport.update({
  id: '/oauth/complete',
  path: '/oauth/complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/device': typeof DeviceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recover': typeof RecoverRoute
  '/set-password': typeof SetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof UnlockRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/welcome/recovery-code': typeof WelcomeRecoveryCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/device': typeof DeviceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recover': typeof RecoverRoute
  '/set-password': typeof SetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof UnlockRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/welcome/recovery-code': typeof WelcomeRecoveryCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/device': typeof DeviceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recover': typeof RecoverRoute
  '/set-password': typeof SetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof UnlockRoute
  '/oauth/complete': typeof OauthCompleteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/welcome/recovery-code': typeof WelcomeRecoveryCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/device'
    | '/projects'
    | '/recover'
    | '/set-password'
    | '/signin'
    | '/signup'
    | '/unlock'
    | '/oauth/complete'
    | '/projects/$projectId'
    | '/welcome/recovery-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/device'
    | '/projects'
    | '/recover'
    | '/set-password'
    | '/signin'
    | '/signup'
    | '/unlock'
    | '/oauth/complete'
    | '/projects/$projectId'
    | '/welcome/recovery-code'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/device'
    | '/projects'
    | '/recover'
    | '/set-password'
    | '/signin'
    | '/signup'
    | '/unlock'
    | '/oauth/complete'
    | '/projects/$projectId'
    | '/welcome/recovery-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DeviceRoute: typeof DeviceRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RecoverRoute: typeof RecoverRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  UnlockRoute: typeof UnlockRoute
  OauthCompleteRoute: typeof OauthCompleteRoute
  WelcomeRecoveryCodeRoute: typeof WelcomeRecoveryCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/recovery-code': {
      id: '/welcome/recovery-code'
      path: '/welcome/recovery-code'
      fullPath: '/welcome/recovery-code'
      preLoaderRoute: typeof WelcomeRecoveryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/oauth/complete': {
      id: '/oauth/complete'
      path: '/oauth/complete'
      fullPath: '/oauth/complete'
      preLoaderRoute: typeof OauthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  DeviceRoute: DeviceRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RecoverRoute: RecoverRoute,
  SetPasswordRoute: SetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  UnlockRoute: UnlockRoute,
  OauthCompleteRoute: OauthCompleteRoute,
  WelcomeRecoveryCodeRoute: WelcomeRecoveryCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
